### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by Aniket21mathur**
- First fixed PyGi warnings.
- Fixed a Nullobject traceback.
- Ported to python3. (Tested with sugar-toolkit v0.114).
@quozl @pro-panda please review.

### CODE REVIEW

**Comment by rhl-bthr** [comment]
Thanks, reviewed.

 - In commit message for 252e2fa, remove the `.` at the end.
 - In commit message for 965fe71, remove the traceback. The description should suffice to know what was the issue, and how does your change fix it
 - Use imperative mood in both the commits. 

See [Making Commits](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits)

**Comment by Aniket21mathur** [comment]
Thanks, made the changes you suggested.

**Comment by quozl** [comment]
Created a pre-port branch "fedora18".  Merged your patches by hand with commit messages in imperative mood.  Thanks!

**Comment by Aniket21mathur** [comment]
Thanks!

**Pull request closed without merging**
