### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by anmol27katyani**
- Updated activity.info
- Ported game.py
- Ported sprites.py

### CODE REVIEW

**Comment by walterbender** [comment]
I am having problems with the sizing of the window opened by the app. It seems to be 1200x900 rather than filling the entire screen until I click a toolbar button to refresh the size. (This is also a problem with the master branch, but can we try to fix it in the port ot GTK3?) And the sixth option is not appearing on the screen, perhaps due to aspect ratio?

**Comment by rhl-bthr** [comment]
Thank you

Reviewed and Tested. 

This does not work with the toolkit suggested in [docs](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md) for porting activities to Python 3. 
Did you test it ?

**Comment by quozl** [comment]
@Pro-Panda, thanks, but in what way does this not work?  Can you please work on the next steps in the toolkit port, so that we can give out .deb or .rpm packages instead of pointing to source only?

**Comment by rhl-bthr** [comment]
Sorry, I should have shared the logs,
```
/usr/share/sugar/activities/nutrition/NutritionActivity.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 164, in main
    module = __import__(module_name)
  File "/usr/share/sugar/activities/nutrition/NutritionActivity.py", line 28, in <module>
    from game import Game, FOOD
  File "/usr/share/sugar/activities/nutrition/game.py", line 30, in <module>
    from food import FOOD_DATA, PYRAMID, NAME, CALS, GROUP, IMAGE
  File "/usr/share/sugar/activities/nutrition/food.py", line 63
    _('cheese'), 07, 1, 'queso.png',
                  ^
SyntaxError: invalid token
Exited with status 1, pid 28925 data (<open file '<fdopen>', mode 'w' at 0x7f61540ee030>, '8db9cbd9bea25147067fe1956545c92d4b8cc267')
```

**Comment by quozl** [comment]
@octamois, please let us know when you've finished your port and the tests pass.

**Comment by rhl-bthr** [comment]
Stale; Needs more work.

@octamois if you plan to fix the same, please reopen the PR with the fixes

**Pull request closed without merging**
