### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by Aniket21mathur**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Good progress.  Is work in progress?  As of 9448228, there are 36 remaining flake8 messages, down from 155.  :grin:

**Comment by Aniket21mathur** [comment]
I fixed the other warnings, although there are still 5 to 6 flake8 warnings, but I think making changes as per  these will affect the functionality. Thanks!

**Comment by quozl** [comment]
Thanks.  I've run flake8 and reviewed each warning;

```
./NutritionActivity.py:120:9: F841 local variable 'group_game_button' is assigned to but never used
./NutritionActivity.py:127:9: F841 local variable 'calorie_game_button' is assigned to but never used
./NutritionActivity.py:134:9: F841 local variable 'pyramid_game_button' is assigned to but never used
./NutritionActivity.py:141:9: F841 local variable 'balance_game_button' is assigned to but never used
./NutritionActivity.py:182:9: F841 local variable 'image_button' is assigned to but never used
./NutritionActivity.py:189:9: F841 local variable 'create_button' is assigned to but never used
```

These are all local variables created by assignment and never used.  Can you explain why the assignment cannot be removed?

```
./NutritionActivity.py:222:21: W503 line break before binary operator
```

This can be changed without affecting function.

```
./game.py:126:80: E501 line too long (83 > 79 characters)
./game.py:136:80: E501 line too long (81 > 79 characters)
```

These too.

```
./sprites.py:261:27: E741 ambiguous variable name 'l'
```

This variable name can be changed.

**Comment by Aniket21mathur** [comment]
> These are all local variables created by assignment and never used. Can you explain why the assignment cannot be removed?

These variable refer to button icons on the toolbar, removing these will remove those icons from the UI. Clicking on those icons results in different game modes.

> This can be changed without affecting function.

Fixing it results in `W504 line break after binary operator` and alternatively fixing one result in another.

> These too.

Thanks, fixed.


> This variable name can be changed

Thanks, fixed.

**Comment by quozl** [comment]
Thanks.  Why does removing the assignment to a function-local variable remove the icons from the UI?  Have you tested that?

**Comment by Aniket21mathur** [comment]
> Why does removing the assignment to a function-local variable remove the icons from the UI?

Thanks,Fixed. Actually I misunderstood things, the variables declared simply call functions `radio_factory` or `button_factory` which adds the button to the toolbar and set its functionality, no need to define a variable for that.

**Comment by quozl** [comment]
Thanks!

**Pull request merged**
